---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/UtahFootball
    - /bin/cp Roster/images $DEPLOYPATH
    - /bin/cp Roster/javascript $DEPLOYPATH
    - /bin/cp Roster/styles $DEPLOYPATH
    - /bin/cp Roster/index.html $DEPLOYPATH
    - /bin/cp Roster/manifest.json $DEPLOYPATH
    - /bin/cp Roster/service-worker.js $DEPLOYPATH
